#!/bin/bash

if [ "$QUERY" = "" ];
then
    echo "please set QUERY"
    exit -1
fi

if [ "$FILTER" = "" ];
then
    FILTER="*"
fi

if [ "$MIRROR_PATH" = "" ];
then
    MIRROR_PATH=/mirror
fi

if [ "$LOG_FILE" = "" ];
then
    LOG_FILE=git-index.log
fi

python -u -m git_indexer --mode=commits --source gitlab --query "$QUERY" --filter "$FILTER" --mirror_path $MIRROR_PATH
