apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml

namespace: default

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: git-indexer-secret
  files:
  - env
