apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-indexer
spec:
  selector:
    matchLabels:
      app: git-indexer
  replicas: 1
  template:
    metadata:
      labels:
        app: git-indexer
    spec:
      containers:
      - name: git-indexer
        image: ghcr.io/vino9org/git-indexer:v0.2.3
        volumeMounts:
        - name: git-indexer-secret-volume
          mountPath: "/etc/secret-volume"
      volumes:
      - name: git-indexer-secret-volume
        secret:
          secretName: git-indexer-secret

---
apiVersion: v1
kind: Service
metadata:
  name: git-indexer
spec:
  type: ClusterIP
  selector:
    app: git-indexer
  ports:
  - name: http
    port: 8000
